version: '3.8'

services:
  angular:
    restart: on-failure
    build:
      context: /ProductStore.App/
      dockerfile: /Build.Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - api-network

  webapi:
    restart: on-failure
    build:
      context: /ProductStore.Api/
      dockerfile: /Dockerfile
      args:
        CERTIFICATE_PASSWORD: "test"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_HTTPS_PORTS=443
    networks:
      - api-network

  mssql:
    build: 
      dockerfile: /Sqlserver.DockerFile
    environment:
      SA_USERNAME: "SA"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - api-network
      
volumes:
  sql-data:

networks:
  api-network:
