version: '3.8'

services:
  angular:
    restart: on-failure
    build:
      context: /productStoreApp/
      dockerfile: /Build.Dockerfile
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://localhost:80/
    networks:
      - api-network

  webapi:
    restart: on-failure
    build:
      context: /ProductStoreApi/
      dockerfile: /Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - api-network

  mssql:
    build: 
      dockerfile: /Sqlserver.DockerFile
    environment:
      SA_USERNAME: "SA"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - api-network
      
volumes:
  sql-data:

networks:
  api-network: