// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductStore.Data.Entities;
using ProductStore.Data.Infrastructure;

#nullable disable

namespace ProductStore.Data.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductSpecification", b =>
                {
                    b.Property<long>("ProductsId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecificationsId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductsId", "SpecificationsId");

                    b.HasIndex("SpecificationsId");

                    b.ToTable("ProductSpecification");

                    b.HasData(
                        new
                        {
                            ProductsId = 1L,
                            SpecificationsId = 9L
                        },
                        new
                        {
                            ProductsId = 2L,
                            SpecificationsId = 10L
                        },
                        new
                        {
                            ProductsId = 3L,
                            SpecificationsId = 11L
                        },
                        new
                        {
                            ProductsId = 4L,
                            SpecificationsId = 12L
                        },
                        new
                        {
                            ProductsId = 5L,
                            SpecificationsId = 13L
                        },
                        new
                        {
                            ProductsId = 6L,
                            SpecificationsId = 14L
                        },
                        new
                        {
                            ProductsId = 7L,
                            SpecificationsId = 15L
                        },
                        new
                        {
                            ProductsId = 8L,
                            SpecificationsId = 9L
                        },
                        new
                        {
                            ProductsId = 9L,
                            SpecificationsId = 10L
                        },
                        new
                        {
                            ProductsId = 10L,
                            SpecificationsId = 11L
                        },
                        new
                        {
                            ProductsId = 11L,
                            SpecificationsId = 12L
                        },
                        new
                        {
                            ProductsId = 12L,
                            SpecificationsId = 13L
                        },
                        new
                        {
                            ProductsId = 13L,
                            SpecificationsId = 14L
                        },
                        new
                        {
                            ProductsId = 14L,
                            SpecificationsId = 15L
                        },
                        new
                        {
                            ProductsId = 15L,
                            SpecificationsId = 9L
                        },
                        new
                        {
                            ProductsId = 16L,
                            SpecificationsId = 10L
                        },
                        new
                        {
                            ProductsId = 17L,
                            SpecificationsId = 11L
                        },
                        new
                        {
                            ProductsId = 18L,
                            SpecificationsId = 12L
                        },
                        new
                        {
                            ProductsId = 19L,
                            SpecificationsId = 13L
                        },
                        new
                        {
                            ProductsId = 20L,
                            SpecificationsId = 14L
                        },
                        new
                        {
                            ProductsId = 21L,
                            SpecificationsId = 15L
                        },
                        new
                        {
                            ProductsId = 22L,
                            SpecificationsId = 9L
                        },
                        new
                        {
                            ProductsId = 23L,
                            SpecificationsId = 10L
                        },
                        new
                        {
                            ProductsId = 24L,
                            SpecificationsId = 11L
                        },
                        new
                        {
                            ProductsId = 25L,
                            SpecificationsId = 12L
                        },
                        new
                        {
                            ProductsId = 26L,
                            SpecificationsId = 13L
                        },
                        new
                        {
                            ProductsId = 27L,
                            SpecificationsId = 14L
                        },
                        new
                        {
                            ProductsId = 28L,
                            SpecificationsId = 15L
                        },
                        new
                        {
                            ProductsId = 29L,
                            SpecificationsId = 13L
                        },
                        new
                        {
                            ProductsId = 30L,
                            SpecificationsId = 14L
                        },
                        new
                        {
                            ProductsId = 31L,
                            SpecificationsId = 15L
                        },
                        new
                        {
                            ProductsId = 1L,
                            SpecificationsId = 4L
                        },
                        new
                        {
                            ProductsId = 2L,
                            SpecificationsId = 3L
                        },
                        new
                        {
                            ProductsId = 3L,
                            SpecificationsId = 6L
                        },
                        new
                        {
                            ProductsId = 7L,
                            SpecificationsId = 3L
                        },
                        new
                        {
                            ProductsId = 8L,
                            SpecificationsId = 6L
                        },
                        new
                        {
                            ProductsId = 9L,
                            SpecificationsId = 6L
                        },
                        new
                        {
                            ProductsId = 29L,
                            SpecificationsId = 6L
                        },
                        new
                        {
                            ProductsId = 30L,
                            SpecificationsId = 5L
                        },
                        new
                        {
                            ProductsId = 31L,
                            SpecificationsId = 5L
                        },
                        new
                        {
                            ProductsId = 25L,
                            SpecificationsId = 5L
                        },
                        new
                        {
                            ProductsId = 26L,
                            SpecificationsId = 6L
                        },
                        new
                        {
                            ProductsId = 27L,
                            SpecificationsId = 4L
                        },
                        new
                        {
                            ProductsId = 28L,
                            SpecificationsId = 4L
                        },
                        new
                        {
                            ProductsId = 4L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 5L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 6L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 10L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 11L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 12L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 13L,
                            SpecificationsId = 1L
                        },
                        new
                        {
                            ProductsId = 14L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 15L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 16L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 17L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 18L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 19L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 20L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 21L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 22L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 23L,
                            SpecificationsId = 2L
                        },
                        new
                        {
                            ProductsId = 24L,
                            SpecificationsId = 2L
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            UserId = 5L
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.CartItem", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("CartId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("StoreDAL.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Alcohol"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Frozen Foods"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Canned"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Sauces"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Energy Drinks"
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Email",
                            PersonId = 1L,
                            Value = "email1@main.com"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Phone",
                            PersonId = 1L,
                            Value = "+380111111111"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Phone",
                            PersonId = 2L,
                            Value = "+380222222222"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Email",
                            PersonId = 3L,
                            Value = "email2@main.com"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Viber",
                            PersonId = 4L,
                            Value = "+380333333333"
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            PositionId = 1L,
                            UserId = 4L
                        },
                        new
                        {
                            Id = 2L,
                            PositionId = 2L,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EmployeeId = 1L,
                            StatusId = 1L,
                            UserComment = "Comment1",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            EmployeeId = 2L,
                            StatusId = 2L,
                            UserComment = "Comment2",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            EmployeeId = 1L,
                            StatusId = 3L,
                            UserComment = "Comment3",
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.OrderDetail", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("smallmoney");

                    b.HasKey("ProductId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            OrderId = 1L,
                            Id = 1L,
                            Quantity = 2,
                            UnitPrice = 12m
                        },
                        new
                        {
                            ProductId = 6L,
                            OrderId = 1L,
                            Id = 1L,
                            Quantity = 8,
                            UnitPrice = 2.3m
                        },
                        new
                        {
                            ProductId = 24L,
                            OrderId = 1L,
                            Id = 1L,
                            Quantity = 3,
                            UnitPrice = 1.7m
                        },
                        new
                        {
                            ProductId = 4L,
                            OrderId = 2L,
                            Id = 2L,
                            Quantity = 1,
                            UnitPrice = 2m
                        },
                        new
                        {
                            ProductId = 2L,
                            OrderId = 2L,
                            Id = 3L,
                            Quantity = 5,
                            UnitPrice = 2.3m
                        },
                        new
                        {
                            ProductId = 1L,
                            OrderId = 3L,
                            Id = 4L,
                            Quantity = 1,
                            UnitPrice = 5m
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "New York, 123 Broadway St",
                            Discount = 0.1m,
                            FirstName = "John",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Los Angeles, 456 Sunset Blvd",
                            Discount = 0.15m,
                            FirstName = "Emily",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Houston, 1011 Main St",
                            Discount = 0.05m,
                            FirstName = "Michael",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 4L,
                            Address = "Phoenix, 1213 Central Ave",
                            Discount = 0.05m,
                            FirstName = "Jessica",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 5L,
                            Address = "Philadelphia, 1415 Walnut St",
                            Discount = 0.2m,
                            FirstName = "David",
                            LastName = "Wilson"
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Helper"
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("smallmoney");

                    b.Property<string>("UnitMeasure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Description = "Martini Brut is a premium sparkling wine that boasts an alcohol content of 11.5%. Known for its fine bubbles and balanced flavor profile, this wine is perfect for celebratory occasions or simply enjoying a glass with friends. The 0.75 liter bottle is ideal for sharing and ensures you have enough to go around. Martini Brut combines elegance and a refreshing taste, making it a versatile choice for any event.",
                            Discount = 0.35m,
                            Name = "Martini Brut 11,5%, 0,75l",
                            Price = 13.37m,
                            UnitMeasure = "bottle"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            Description = "Hankey Bannister is a renowned blended Scotch whisky known for its smooth and balanced flavor profile. This 1-liter bottle of Hankey Bannister offers ample supply for your enjoyment or for sharing with friends and family. Crafted with a blend of carefully selected malt and grain whiskies, Hankey Bannister delivers a rich and satisfying taste experience with every sip. Whether enjoyed neat, on the rocks, or as part of your favorite cocktail, Hankey Bannister promises a delightful whisky experience.",
                            Discount = 0.6m,
                            Name = "Hankey Bannister, 1l",
                            Price = 24.78m,
                            UnitMeasure = "bottle"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 1L,
                            Description = "Corona Extra is a popular Mexican beer known for its refreshing taste and iconic presentation. Brewed since 1925, this pale lager has become a symbol of relaxation and enjoyment worldwide. With its light and crisp flavor profile, Corona Extra is perfect for any occasion, whether you're lounging on the beach, hosting a barbecue, or simply unwinding after a long day. Enjoyed best when served ice-cold with a wedge of lime, Corona Extra delivers a smooth and satisfying drinking experience that pairs effortlessly with sunny days and good company.",
                            Discount = 0.37m,
                            Name = "Corona Extra, 0,33l",
                            Price = 1.54m,
                            UnitMeasure = "bottle"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 2L,
                            Description = "Indulge in the timeless simplicity of the classic ham sandwich. Made with thinly sliced ham nestled between two slices of your favorite bread, this sandwich is a satisfying combination of flavors and textures. Whether you're packing a lunch, need a quick bite, or craving a comforting snack, the classic ham sandwich is always a delicious choice. Add your favorite condiments and toppings like lettuce, tomato, cheese, or mustard to customize it to your taste preferences. With its savory ham and soft bread, this sandwich is a timeless favorite that never fails to hit the spot.",
                            Discount = 0.2m,
                            Name = "Sandwich with ham, 200g",
                            Price = 1.44m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 2L,
                            Description = "Savor the delightful combination of sweet cherries nestled within a soft, fluffy bun with our Cherry Bun Delight. Perfect for breakfast, dessert, or a delightful snack, this treat offers a burst of fruity flavor in every bite. Each bun is lovingly filled with succulent cherries, creating a harmonious blend of tartness and sweetness that tantalizes the taste buds. Whether enjoyed with a cup of coffee in the morning or as a delightful afternoon treat, our Cherry Bun Delight is sure to brighten your day with its irresistible flavor and comforting texture.",
                            Discount = 0.2m,
                            Name = "Bun with cherry",
                            Price = 1.36m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 3L,
                            Description = "Indulge in the exquisite taste and tender texture of our Beef Steak Wet Aged, expertly crafted to perfection. Each succulent bite promises a symphony of flavors, from the rich umami of premium beef to the subtle hints of natural juices that enhance every mouthful. Wet aging ensures optimal tenderness and juiciness, allowing the meat to reach its peak flavor potential. Sourced from the finest cuts of beef, our steak is hand-selected for its marbling and quality, guaranteeing a dining experience that surpasses expectations. Whether seared to perfection on the grill or pan-fried to your desired level of doneness, our Beef Steak Wet Aged is a culinary masterpiece that elevates any meal.",
                            Discount = 0.1m,
                            Name = "Beef steak Wet Aged, 100g",
                            Price = 12.90m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 4L,
                            Description = "Description6",
                            Discount = 0m,
                            Name = "Schweppes pomegranate, 1l",
                            Price = 1.15m,
                            UnitMeasure = "bottle"
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 4L,
                            Description = "Indulge in the bold and refreshing flavor of Dr. Pepper Cherry, a delightful twist on the classic soda favorite. Bursting with the essence of ripe cherries combined with the signature blend of 23 flavors found in Dr. Pepper, each sip delivers a symphony of taste sensations that tantalize the palate. Whether enjoyed on its own over ice or used as a mixer in your favorite cocktails, Dr. Pepper Cherry is the perfect beverage choice for any occasion. With its distinctive cherry-infused aroma and satisfyingly fizzy texture, this iconic soda will leave you craving more with every sip.",
                            Discount = 0.19m,
                            Name = "Dr.Pepper Cherry, 0,33l",
                            Price = 0.92m,
                            UnitMeasure = "can"
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 4L,
                            Description = "Embark on an exhilarating journey of citrusy refreshment with Mountain Dew, the iconic soft drink that energizes and invigorates with every sip. Bursting with bold flavors and a vibrant neon-green hue, Mountain Dew is a beloved beverage that ignites the senses and fuels adventure. With its unique blend of citrus flavors and a touch of sweetness, this fizzy drink delivers an unmistakable taste that's as exhilarating as scaling a mountain peak. Whether you're tackling the great outdoors or simply kicking back with friends, Mountain Dew is the perfect companion for those who thirst for excitement.",
                            Discount = 0.22m,
                            Name = "Mountain Dew, 0,33l",
                            Price = 1.26m,
                            UnitMeasure = "can"
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 5L,
                            Description = "Indulge in the irresistible crunch and savory taste of Pringles Sour Cream & Onion Flavor. Each bite-sized crisp is meticulously seasoned with a delectable blend of tangy sour cream and zesty onion flavors, creating a mouthwatering snack sensation that's hard to resist. Whether you're snacking solo, sharing with friends, or enjoying a movie night at home, Pringles Sour Cream & Onion Flavor offers the perfect combination of flavor and crunch to satisfy your snack cravings. Packed in a convenient resealable tube, these Pringles are ideal for on-the-go munching or as a flavorful addition to any party spread.",
                            Discount = 0m,
                            Name = "Pringles with sour cream and onion flavor, 165g",
                            Price = 3.60m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 5L,
                            Description = "Indulge in the unmatched crispiness and flavorful taste of Pringles chips with chili-lime flavor. Each crispy chip is infused with the bold flavor of spicy chili and refreshing lime, creating an incredibly appetizing sensation that's hard to resist. Whether you're snacking alone or sharing with friends, Pringles with chili-lime flavor are sure to satisfy your taste buds with every bite.",
                            Discount = 0m,
                            Name = "Pringles with hot chili-lime flavor, 158g",
                            Price = 3.60m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 5L,
                            Description = "Enjoy the delightful taste of Pringles chips with cheese flavor. Each crispy chip is bursting with rich and savory cheese flavor that will tantalize your taste buds with every bite. Perfect for snacking on the go or sharing with friends, Pringles cheese flavor chips are a delicious and satisfying treat for any occasion.",
                            Discount = 0m,
                            Name = "Pringles cheese, 165g",
                            Price = 3.60m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 6L,
                            Description = "Indulge in the delightful taste of Schulstad Croissants, made with traditional recipes and the finest ingredients. Each 480g pack contains perfectly baked, flaky croissants that are golden on the outside and soft on the inside. These croissants are ideal for breakfast, a quick snack, or as an accompaniment to your favorite meals.",
                            Discount = 0.2m,
                            Name = "Croissants Shulstad, 480 g",
                            Price = 6.230m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 6L,
                            Description = "Experience the refreshing and exotic flavors of Tonitto Sorbet with Mango and Passion Fruit. This 310g tub of sorbet is a perfect blend of tropical mango and tangy passion fruit, delivering a deliciously smooth and refreshing treat. Made with real fruit and crafted to perfection, Tonitto Sorbet offers a guilt-free indulgence for any time of the day.",
                            Discount = 0m,
                            Name = "Sorbet Tonitto with mango and passion fruit, 310g",
                            Price = 3.60m,
                            UnitMeasure = "tube"
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 6L,
                            Description = "Discover a luxurious treat with Franui Raspberries in White and Milk Chocolate. Each 150g pack features premium fresh-frozen raspberries, perfectly coated in a layer of smooth white chocolate followed by a rich milk chocolate shell. This decadent combination of tangy raspberries and creamy chocolate offers an exquisite taste sensation, perfect for satisfying your sweet cravings.",
                            Discount = 0.35m,
                            Name = "Raspberries Franui in white and milk chocolate, fresh frozen, 150g",
                            Price = 5.68m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 6L,
                            Description = "Savor the wholesome goodness of Liveg Veg Cutlet made from tofu and seitan. Each 160g pack offers a delicious and nutritious plant-based alternative that's perfect for anyone looking to incorporate more vegetarian options into their diet. These cutlets are expertly crafted to deliver a satisfying texture and rich flavor, making them an ideal choice for a quick and healthy meal.",
                            Discount = 0.14m,
                            Name = "Liveg Veg Cutlet from tofu and seitan, 160g",
                            Price = 4.19m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 6L,
                            Description = "Indulge in the rich and decadent flavor of \"Belgian Chocolate\" Ice Cream. This 300g tub offers a luxurious dessert experience, featuring velvety smooth ice cream made with the finest Belgian chocolate. Perfect for chocolate lovers, this ice cream delivers an intense, creamy, and unforgettable taste sensation that will satisfy your sweet tooth.",
                            Discount = 0m,
                            Name = "Ice cream \"Belgian chocolate\", 300g",
                            Price = 6.67m,
                            UnitMeasure = "tube"
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 7L,
                            Description = "Enhance your culinary creations with Otto Botti Pitted Black Olives. Each 300ml jar is filled with carefully selected, high-quality black olives that are pitted for your convenience. These olives are perfect for a wide range of dishes, from salads and pizzas to pasta and tapas, offering a rich and savory flavor that complements any meal.",
                            Discount = 0m,
                            Name = "Otto Botti pitted black olives, 300 ml",
                            Price = 1.36m,
                            UnitMeasure = "can"
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 7L,
                            Description = "Bring the authentic taste of Italy to your kitchen with Fiorino Whole Peeled Tomatoes in Tomato Juice. Each 400g can is packed with sun-ripened tomatoes, carefully peeled and preserved in rich tomato juice to retain their natural flavor and freshness. Perfect for a variety of dishes, these tomatoes are a versatile and essential ingredient for any home cook.",
                            Discount = 0m,
                            Name = "Whole peeled Fiorino tomatoes in tomato juice, 400g",
                            Price = 1.61m,
                            UnitMeasure = "can"
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 7L,
                            Description = "Discover the exquisite taste of Iberica Black Mini Stoneless Olives, a gourmet delight straight from the Mediterranean. Sourced from the famed olive groves of the Iberian Peninsula, these mini olives are hand-selected for their exceptional quality and flavor. Packed without stones, they offer a convenient and mess-free way to enjoy the rich and robust taste of premium black olives.",
                            Discount = 0m,
                            Name = "Iberica black mini stoneless olives, 300g",
                            Price = 2.60m,
                            UnitMeasure = "can"
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 9L,
                            Description = "Elevate your dishes with the authentic taste of Barilla Pesto alla Genovese. This 190g jar of premium pesto sauce is made with fresh basil, Parmigiano Reggiano cheese, and rich olive oil, delivering a vibrant and aromatic flavor. Perfect for pasta, sandwiches, or as a marinade, Barilla Pesto alla Genovese adds a delightful Italian touch to any meal.",
                            Discount = 0m,
                            Name = "Sauce Barilla Pesto alla Genovese, 190g",
                            Price = 3.05m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 22L,
                            CategoryId = 8L,
                            Description = "Experience the authentic taste of Italy with Garofalo \"Penne Rigate\" No. 70 Bio Pasta. Crafted with care using organic ingredients, this 500g pack of penne rigate pasta offers a perfect blend of tradition and quality. Made from the finest durum wheat semolina, each piece of pasta is bronze-extruded to create a rough texture that holds sauces beautifully, ensuring a delightful dining experience with every bite.",
                            Discount = 0.3m,
                            Name = "Pasta Garofalo \"Penne Rigate\" No. 70 Bio, 500g",
                            Price = 2.95m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 23L,
                            CategoryId = 8L,
                            Description = "Introducing Riscossa \"Serpentine\" No. 51 Pasta, a unique and versatile addition to your culinary repertoire. This 500g pack features serpentine-shaped pasta meticulously crafted to hold sauces and flavors in every twist and turn. Made from premium durum wheat semolina, Riscossa pasta undergoes a traditional bronze extrusion process, ensuring an authentic texture that pairs perfectly with a variety of sauces.",
                            Discount = 0.2m,
                            Name = "Pasta Riscossa \"Serpentine\" No. 51, 500g",
                            Price = 1.49m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 24L,
                            CategoryId = 8L,
                            Description = "Discover the delightful Garofalo \"Orzo\" Pasta, a versatile and elegant addition to your culinary creations. This 500g pack of orzo pasta offers a unique grain-like shape that resembles barley, making it perfect for a variety of dishes, from soups and salads to casseroles and pilafs. Crafted with the finest durum wheat semolina, Garofalo ensures superior quality and taste in every bite.",
                            Discount = 0m,
                            Name = "Pasta Garofalo \"Orzo\", 500g",
                            Price = 2.46m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 25L,
                            CategoryId = 9L,
                            Description = "Experience the classic taste of Heinz Mild Ketchup, a beloved condiment enjoyed by families around the world. This 570g bottle features Heinz's signature ketchup recipe, crafted with ripe tomatoes, a blend of spices, and a hint of sweetness. Perfectly balanced and irresistibly smooth, Heinz Mild Ketchup is a versatile addition to burgers, fries, sandwiches, and more.",
                            Discount = 0m,
                            Name = "Ketchup Heinz Mild, 570g",
                            Price = 4.32m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 26L,
                            CategoryId = 9L,
                            Description = "Get ready to add a zing to your meals with Mr. Caramba's \"Sweet Chili\" Sauce. This 300g bottle packs a punch of flavor with its perfect blend of sweetness and heat. Ideal as a dipping sauce, marinade, or condiment, Mr. Caramba's Sweet Chili Sauce adds a delicious kick to everything from chicken wings to spring rolls.",
                            Discount = 0m,
                            Name = "Sauce Mr. Caramba \"Sweet chili\", 300g",
                            Price = 5.43m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 27L,
                            CategoryId = 9L,
                            Description = "Experience the authentic taste of Achva Tahini, a rich and creamy sesame paste that's perfect for adding depth and flavor to your favorite dishes. Made from carefully selected sesame seeds, this 500g jar of tahini offers a smooth texture and a nutty taste that pairs well with both sweet and savory recipes. Whether you're making hummus, salad dressings, or baked goods, Achva Tahini is a versatile pantry staple that will elevate your cooking to new heights.",
                            Discount = 0m,
                            Name = "Tahini Achva, 500g",
                            Price = 5.68m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 28L,
                            CategoryId = 9L,
                            Description = "Elevate your dishes with the rich and flavorful Heinz Garlic Sauce. This 400ml bottle is packed with the irresistible taste of garlic, offering a perfect balance of savory goodness and aromatic notes. Whether you're dipping, drizzling, or cooking, Heinz Garlic Sauce adds a delicious twist to a variety of meals, from sandwiches and salads to meats and vegetables.",
                            Discount = 0m,
                            Name = "Sauce Heinz Garlic, 400 ml",
                            Price = 4.19m,
                            UnitMeasure = "unit"
                        },
                        new
                        {
                            Id = 29L,
                            CategoryId = 10L,
                            Description = "Fuel your day with the refreshing and invigorating Burn Mango Energy Drink. This 250ml can bursts with the exotic flavor of ripe mango, combined with the powerful energy boost of Burn's signature blend. Perfect for those moments when you need a pick-me-up, Burn Mango Energy Drink delivers a tropical taste sensation that revives your senses and keeps you going.",
                            Discount = 0m,
                            Name = "Energy drink Burn mango, 250 ml",
                            Price = 1m,
                            UnitMeasure = "can"
                        },
                        new
                        {
                            Id = 30L,
                            CategoryId = 10L,
                            Description = "Unleash the beast with Monster Energy \"The Doctor\" Drink in a 500ml can. This exhilarating beverage offers a fusion of tropical citrus flavors, delivering a bold and electrifying taste experience. Packed with Monster's signature energy blend, \"The Doctor\" provides the perfect kick to fuel your day, whether you're hitting the gym, studying for exams, or need an extra boost during a long day at work.",
                            Discount = 0m,
                            Name = "Energy drink Monster Energy The Doctor, 0.5l",
                            Price = 1.7m,
                            UnitMeasure = "can"
                        },
                        new
                        {
                            Id = 31L,
                            CategoryId = 10L,
                            Description = "Unleash your inner royalty with Monster Energy \"Monarch\" Drink, the ultimate companion for conquering your day. This electrifying beverage embodies power, vitality, and a taste fit for kings and queens. With a symphony of exhilarating flavors and a potent energy blend, \"Monarch\" reigns supreme among energy drinks.",
                            Discount = 0.25m,
                            Name = "Energy drink Monster Energy Monarch, 0.5l",
                            Price = 2.2m,
                            UnitMeasure = "can"
                        });
                });


			string variable = Environment.GetEnvironmentVariable("IsDockerContainer") ?? string.Empty;

			// Path for local 
			string seedDir = "..\\StoreDAL\\SeedImages\\";

			// Path for Docker container
			if (bool.TryParse(variable, out bool isDockerContainer) && isDockerContainer)
			{
				seedDir = "./StoreDAL/SeedImages/";
			}

			modelBuilder.Entity("StoreDAL.Entities.ProductImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("image");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Image = File.ReadAllBytes($"{seedDir}{1}.webp"),
							ProductId = 1L
                        },
						new
						{
							Id = 2L,
							Image = File.ReadAllBytes($"{seedDir}{2}.webp"),
							ProductId = 2L
						},
						new
						{
							Id = 3L,
							Image = File.ReadAllBytes($"{seedDir}{3}.webp"),
							ProductId = 3L
						},
						new
						{
							Id = 4L,
							Image = File.ReadAllBytes($"{seedDir}{4}.webp"),
							ProductId = 4L
						},
						new
						{
							Id = 5L,
							Image = File.ReadAllBytes($"{seedDir}{5}.webp"),
							ProductId = 5L
						},
						new
						{
							Id = 6L,
							Image = File.ReadAllBytes($"{seedDir}{6}.webp"),
							ProductId = 6L
						},
						new
						{
							Id = 7L,
							Image = File.ReadAllBytes($"{seedDir}{7}.webp"),
							ProductId = 7L
						},
						new
						{
							Id = 8L,
							Image = File.ReadAllBytes($"{seedDir}{8}.webp"),
							ProductId = 8L
						},
						new
						{
							Id = 9L,
							Image = File.ReadAllBytes($"{seedDir}{9}.webp"),
							ProductId = 9L
						},
						new
						{
							Id = 10L,
							Image = File.ReadAllBytes($"{seedDir}{10}.webp"),
							ProductId = 10L
						},
						new
						{
							Id = 11L,
							Image = File.ReadAllBytes($"{seedDir}{11}.webp"),
							ProductId = 11L
						},
						new
						{
							Id = 12L,
							Image = File.ReadAllBytes($"{seedDir}{12}.webp"),
							ProductId = 12L
						},
						new
						{
							Id = 13L,
							Image = File.ReadAllBytes($"{seedDir}{13}.webp"),
							ProductId = 13L
						},
						new
						{
							Id = 14L,
							Image = File.ReadAllBytes($"{seedDir}{14}.webp"),
							ProductId = 14L
						},
						new
						{
							Id = 15L,
							Image = File.ReadAllBytes($"{seedDir}{15}.webp"),
							ProductId = 15L
						},
						new
						{
							Id = 16L,
							Image = File.ReadAllBytes($"{seedDir}{16}.webp"),
							ProductId = 16L
						},
						new
						{
							Id = 17L,
							Image = File.ReadAllBytes($"{seedDir}{17}.webp"),
							ProductId = 17L
						},
						new
						{
							Id = 18L,
							Image = File.ReadAllBytes($"{seedDir}{18}.webp"),
							ProductId = 18L
						},
						new
						{
							Id = 19L,
							Image = File.ReadAllBytes($"{seedDir}{19}.webp"),
							ProductId = 19L
						},
						new
						{
							Id = 20L,
							Image = File.ReadAllBytes($"{seedDir}{20}.webp"),
							ProductId = 20L
						},
						new
						{
							Id = 21L,
							Image = File.ReadAllBytes($"{seedDir}{21}.webp"),
							ProductId = 21L
						},
						new
						{
							Id = 22L,
							Image = File.ReadAllBytes($"{seedDir}{22}.webp"),
							ProductId = 22L
						},
						new
						{
							Id = 23L,
							Image = File.ReadAllBytes($"{seedDir}{23}.webp"),
							ProductId = 23L
						},
						new
						{
							Id = 24L,
							Image = File.ReadAllBytes($"{seedDir}{24}.webp"),
							ProductId = 24L
						},
						new
						{
							Id = 25L,
							Image = File.ReadAllBytes($"{seedDir}{25}.webp"),
							ProductId = 25L
						},
						new
						{
							Id = 26L,
							Image = File.ReadAllBytes($"{seedDir}{26}.webp"),
							ProductId = 26L
						},
						new
						{
							Id = 27L,
							Image = File.ReadAllBytes($"{seedDir}{27}.webp"),
							ProductId = 27L
						},
						new
						{
							Id = 28L,
							Image = File.ReadAllBytes($"{seedDir}{28}.webp"),
							ProductId = 28L
						},
						new
						{
							Id = 29L,
							Image = File.ReadAllBytes($"{seedDir}{29}.webp"),
							ProductId = 29L
						},
						new
						{
							Id = 30L,
							Image = File.ReadAllBytes($"{seedDir}{30}.webp"),
							ProductId = 30L
						},
						new
						{
							Id = 31L,
							Image = File.ReadAllBytes($"{seedDir}{31}.webp"),
							ProductId = 31L
						});
                });

            modelBuilder.Entity("StoreDAL.Entities.Specification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specifications");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Weight",
                            Value = "1 kg"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Weight",
                            Value = "0.5 kg"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Volume",
                            Value = "1 l"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Volume",
                            Value = "0.75 l"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Volume",
                            Value = "0.25 l"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Volume",
                            Value = "0.5 l"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Weight",
                            Value = "1 kg"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Size",
                            Value = "15x2x3"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Manufacturer",
                            Value = "United States"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Manufacturer",
                            Value = "Canada"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Manufacturer",
                            Value = "Japan"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Manufacturer",
                            Value = "United Kingdom"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Manufacturer",
                            Value = "Germany"
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Manufacturer",
                            Value = "France"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Manufacturer",
                            Value = "Brazil"
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Waiting for approve"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "In process"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Delivered"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Canceled"
                        });
                });

            modelBuilder.Entity("StoreDAL.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsActive = true,
                            Password = "$2a$11$QxP6GG54zUOzEhLs2CORNuNOfokAkM09Op5MFN0oLkTeX3rS/vjsO",
                            PersonId = 1L,
                            RefreshToken = "",
                            Username = "johnsmith"
                        },
                        new
                        {
                            Id = 2L,
                            IsActive = true,
                            Password = "$2a$11$nVp1qAK9YwOi5LNpFAXfR.SK07.DRBt4KnvIfdpOnahEQO6wJouOy",
                            PersonId = 2L,
                            RefreshToken = "",
                            Username = "emilyjohnson"
                        },
                        new
                        {
                            Id = 3L,
                            IsActive = true,
                            Password = "$2a$11$yD69ysc/wPKgIWpLJq2HjOLfDRPymOhlz8jRVoj4sv57L9G.jjSsq",
                            PersonId = 3L,
                            RefreshToken = "",
                            Username = "michaelbrown"
                        },
                        new
                        {
                            Id = 4L,
                            IsActive = true,
                            Password = "$2a$11$sj9d8CY2L0ozSoQfdvce5.TpCiI.dr6iejTOmWBAE1xqJ9rj/wRw6",
                            PersonId = 4L,
                            RefreshToken = "",
                            Username = "jessicadavis"
                        },
                        new
                        {
                            Id = 5L,
                            IsActive = false,
                            Password = "$2a$11$n/bFeF3Xh.QHYwQ1RL6GyuvNe.tytw2NnWlQA0RSEVe6cMFbXRQeu",
                            PersonId = 5L,
                            RefreshToken = "",
                            Username = "davidwilson"
                        });
                });

            modelBuilder.Entity("ProductSpecification", b =>
                {
                    b.HasOne("StoreDAL.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreDAL.Entities.Specification", null)
                        .WithMany()
                        .HasForeignKey("SpecificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StoreDAL.Entities.Cart", b =>
                {
                    b.HasOne("StoreDAL.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("StoreDAL.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoreDAL.Entities.CartItem", b =>
                {
                    b.HasOne("StoreDAL.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreDAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreDAL.Entities.Contact", b =>
                {
                    b.HasOne("StoreDAL.Entities.Person", "Person")
                        .WithMany("Contacts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StoreDAL.Entities.Employee", b =>
                {
                    b.HasOne("StoreDAL.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoreDAL.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("StoreDAL.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoreDAL.Entities.Order", b =>
                {
                    b.HasOne("StoreDAL.Entities.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoreDAL.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoreDAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StoreDAL.Entities.OrderDetail", b =>
                {
                    b.HasOne("StoreDAL.Entities.Order", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoreDAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreDAL.Entities.Product", b =>
                {
                    b.HasOne("StoreDAL.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StoreDAL.Entities.ProductImage", b =>
                {
                    b.HasOne("StoreDAL.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StoreDAL.Entities.User", b =>
                {
                    b.HasOne("StoreDAL.Entities.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("StoreDAL.Entities.User", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StoreDAL.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("StoreDAL.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StoreDAL.Entities.Employee", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("StoreDAL.Entities.Order", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("StoreDAL.Entities.Person", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("StoreDAL.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("StoreDAL.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("StoreDAL.Entities.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
